name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Make configure script executable
      run: chmod +x configure

    - name: Run configure script
      run: ./configure

    - name: Build project
      run: make
